import React from 'react'
import CommentList from './CommentList' 
import CommentForm from './CommentForm'
import data from '../api/data'
    
class CommentBox extends React.Component {
    constructor(props) {
        super(props);
        this.state = {data: data} 
    }
    
    
    handleCommentSubmit(comment) {
        var comments = this.state.data;
        // Optimistically set an id on the new comment. It will be replaced by an
        // id generated by the server. In a production application you would likely
        // not use Date.now() for this and would have a more robust system in place.
        comment.id = Date.now();
        var newComments = comments.concat([comment]);
        this.setState({data: newComments});
        
    }
    
    render() {
        return (
        <div className="CommentBox">
            <h1>Comments</h1> 
                <CommentList data={this.state.data}/>  
                <CommentForm onCommentSubmit={this.handleCommentSubmit.bind(this)} /> 
        </div>        
        );
    }
} 

export default CommentBox;  